// ═══ MENU CONFIGURATION — 7 GROUPES ═══
// Nettoyé : seuls les IDs avec un case dans _registry.js
export const MENU = [
  { id: '_g1', label: 'TABLEAU DE BORD', icon: '◫', group: true },
  { id: 'dashboard',    label: 'Dashboard Principal',  icon: '◫',  g: 1 },
  { id: 'smartalerts',  label: 'Smart Alerts',         icon: '🔔', g: 1 },
  { id: 'notifications',label: 'Notifications',        icon: '🔔', g: 1 },
  { id: 'analytics',    label: 'Analytics',            icon: '📈', g: 1 },

  { id: '_g2', label: 'GESTION RH', icon: '◉', group: true },
  { id: 'employees',       label: 'Liste Employés',        icon: '◉',  g: 2 },
  { id: 'dashrh',          label: 'Dashboard RH',          icon: '👥', g: 2 },
  { id: 'dashabsent',      label: 'Dash Absentéisme',      icon: '📊', g: 2 },
  { id: 'gestionabs',      label: 'Gestion Absences',      icon: '🗓', g: 2 },
  { id: 'workflowAbs',     label: 'Workflow Absences',     icon: '🏖', g: 2 },
  { id: 'planifconges',    label: 'Planning Congés',       icon: '📅', g: 2 },
  { id: 'onboarding',      label: 'Onboarding',            icon: '🆕', g: 2 },
  { id: 'contratgen',      label: 'Contrats Légaux',       icon: '📝', g: 2 },
  { id: 'contratsmenu',    label: 'Contrats & Documents',  icon: '▣',  g: 2 },
  { id: 'proceduresrh',    label: 'Procédures RH (64)',    icon: '📋', g: 2 },
  { id: 'portailclient',   label: 'Portail Client',        icon: '🌐', g: 2 },

  { id: '_g3', label: 'PAIE & CALCULS', icon: '💰', group: true },
  { id: 'payslip',       label: 'Fiches de Paie',           icon: '◈',  g: 3 },
  { id: 'gestionprimes', label: '57 Primes & Avantages',    icon: '🎁', g: 3 },
  { id: 'calcinstant',   label: 'Calcul Instantané',        icon: '🔁', g: 3 },
  { id: 'baremescp',     label: 'Barèmes CP',               icon: '📊', g: 3 },
  { id: 'seuilssociaux', label: 'Seuils Sociaux',           icon: '📐', g: 3 },
  { id: 'cloture',       label: 'Clôture Mensuelle',        icon: '🔄', g: 3 },
  { id: 'optifiscale',   label: 'Optimisation Fiscale',     icon: '💡', g: 3 },
  { id: 'payrollhub',    label: 'Payroll Hub',              icon: '💰', g: 3 },
  { id: 'transversalcp', label: 'Transversal CP',           icon: '📋', g: 3 },

  { id: '_g4', label: 'DÉCLARATIONS & COMPTABILITÉ', icon: '◆', group: true },
  { id: 'declarations',  label: 'Déclarations ONSS/SPF',    icon: '📡', g: 4 },
  { id: 'batchdecl',     label: 'Déclarations Batch',       icon: '📋', g: 4 },
  { id: 'exportbatch',   label: 'Export Batch',             icon: '📦', g: 4 },
  { id: 'facturation',   label: 'Facturation',              icon: '🧾', g: 4 },
  { id: 'legal',         label: 'Juridique & Veille',       icon: '⚖',  g: 4 },
  { id: 'lois',          label: 'Lois Belges 2026',         icon: '📜', g: 4 },

  { id: '_g5', label: 'COMMERCIAL & PROSPECTS', icon: '🎯', group: true },
  { id: 'guidecommercial', label: 'Guide Commercial',       icon: '📊', g: 5 },
  { id: 'gendocsjur',      label: 'Docs Juridiques',        icon: '📜', g: 5 },
  { id: 'portailclient',   label: 'Portail Client',         icon: '🌐', g: 5 },

  { id: '_g6', label: 'MANDATS & PRIMES EMPLOI', icon: '🏛', group: true },
  { id: 'connexionshub',  label: 'Hub Connexions H24',           icon: '🔗', g: 6 },
  { id: 'mandatonss',     label: 'Mandat ONSS/Mahis',            icon: '🏛', g: 6 },
  { id: 'belcotaxmandat', label: 'Belcotax — Mandat Fiscal',     icon: '📄', g: 6 },
  { id: 'ged',            label: 'GED Documents',                icon: '📁', g: 6 },
  { id: 'integrations',   label: 'Intégrations',                 icon: '🔌', g: 6 },

  { id: '_g7', label: 'ADMINISTRATION', icon: '👑', group: true },
  { id: 'admin',            label: 'Admin',                icon: '👑', g: 7 },
  { id: 'permissions',      label: 'Rôles & Permissions',  icon: '🔐', g: 7 },
  { id: 'authroles',        label: 'Auth & Rôles',         icon: '🔐', g: 7 },
  { id: 'adminbaremes',     label: 'Admin Barèmes',        icon: '⚙️', g: 7 },
  { id: 'auditsecuritecode',label: 'Audit Sécurité Code',  icon: '🛡', g: 7 },
  { id: 'aureussuite',      label: 'Aureus IA Suite',      icon: '🔷', g: 7 },
  { id: 'autopilot',        label: 'Autopilot',            icon: '🤖', g: 7 },
  { id: 'compliance',       label: 'Compliance Radar',     icon: '🛡', g: 7 },
  { id: 'massengine',       label: 'Mass Engine',          icon: '🏭', g: 7 },
  { id: 'notifications',    label: 'Notifications',        icon: '🔔', g: 7 },
  { id: 'piloteauto',       label: 'Pilote Auto Total',    icon: '🏎️', g: 7 },
  { id: 'portalmanager',    label: 'Gestion Portails',     icon: '🏢', g: 7 },
  { id: 'securitedata',     label: 'Sécurité Données',     icon: '🔒', g: 7 },
  { id: 'settings',         label: 'Paramètres',           icon: '⚙️', g: 7 },
  { id: 'smartops',         label: 'Smart Ops Center',     icon: '🎯', g: 7 },
  { id: 'team',             label: 'Équipe',               icon: '👥', g: 7 },
];

export const GROUPS = MENU.filter(m => m.group);
export const getGroupItems = (gNum) => MENU.filter(m => m.g === gNum && !m.group);

// ═══ INDEX SOUS-SECTIONS — RECHERCHE CONTEXTUELLE ═══
export const SEARCH_SUBSECTIONS = [
  {
    id: 'payslip',
    anchor: 'section-onss-cotisations',
    icon: '⚡',
    label: 'ONSS & Cotisations',
    sub: 'Fiche de paie — Paramètres légaux',
    keywords: ['onss','cotisation','13,07','25,07','cotisations sociales','securite sociale','travailleur','patronal','ouvrier','108%','rmmmg','co2','majoration'],
  },
  {
    id: 'payslip',
    anchor: 'section-precompte',
    icon: '🧾',
    label: 'Précompte professionnel',
    sub: 'Fiche de paie — Paramètres légaux',
    keywords: ['precompte','précompte','pp','impot','impôt','tranches','taux','26,75','42,80','48,15','53,50','bonus emploi','quotite','quotité','seuil','fiscal','fiscalite','fiscalité'],
  },
  {
    id: 'payslip',
    anchor: 'section-csss',
    icon: '📊',
    label: 'CSSS — Cotisation spéciale SS',
    sub: 'Fiche de paie — Paramètres légaux',
    keywords: ['csss','cotisation speciale','spéciale','cotisation special','revenu imposable','tranche csss','securite sociale speciale'],
  },
  {
    id: 'payslip',
    anchor: 'section-avantages',
    icon: '🎁',
    label: 'Avantages & Frais propres',
    sub: 'Fiche de paie — Paramètres légaux',
    keywords: ['avantages','frais propres','cheques repas','chèques-repas','eco cheques','éco-chèques','ecocheques','forfait bureau','teletravail','télétravail','km voiture','kilometrique','kilométrique','frais','depenses','dépenses','repas','indemnite','indemnité'],
  },
  {
    id: 'payslip',
    anchor: 'section-saisies',
    icon: '⚖️',
    label: 'Saisies sur salaire',
    sub: 'Fiche de paie — Paramètres légaux',
    keywords: ['saisie','saisies','salaire','art 1409','1409','garnish','garnissement','immunite','immunité','enfant','saisie salaire','baremes saisie'],
  },
  {
    id: 'payslip',
    anchor: 'section-af',
    icon: '👶',
    label: 'Allocations familiales',
    sub: 'Fiche de paie — Paramètres légaux',
    keywords: ['allocations familiales','allocation familiale','af','enfant','iriscare','aviq','groeipakket','bruxelles','wallonie','flandre','region','bxl','wal','vl'],
  },
  {
    id: 'payslip',
    anchor: 'section-cp',
    icon: '📋',
    label: 'Barème sectoriel CP',
    sub: 'Fiche de paie — Paramètres légaux',
    keywords: ['bareme','barème','cp','commission paritaire','sectoriel','classe','minimum','minima','secteur','cp 200','cp 111','cp 118','cp 119','cp 124','cp 140','cp 302','cp 330'],
  },
];
