// ═══ MENU CONFIGURATION — 5 GROUPES, 35 ITEMS ═══
// Refactorisé : suppression des 107 doublons et items techniques inutiles
// Les fonctions avancées sont accessibles via onglets internes aux pages

export const MENU = [

  // ── ACCUEIL ──────────────────────────────────────────────────
  { id: '_g1', label: 'ACCUEIL', icon: '◫', group: true },
  { id: 'dashboard',   label: 'Dashboard',      icon: '◫', g: 1 },
  { id: 'embaucheaz',  label: 'Embauche A→Z',   icon: '🚀', g: 1 },
  { id: 'smartalerts',    label: 'Smart Alertes',      icon: '🔔', g: 1 },
  { id: 'notifications', label: 'Notifications', icon: '🔔', g: 1 },

  // ── EMPLOYÉS ─────────────────────────────────────────────────
  { id: '_g2', label: 'EMPLOYÉS', icon: '👥', group: true },
  { id: 'employees',    label: 'Liste & Fiches',   icon: '👤', g: 2 },
  { id: 'onboarding',  label: 'Nouvel employé',   icon: '🆕', g: 2 },
  { id: 'aidesembauche', label: 'Aides à l\'embauche', icon: '💶', g: 2, keywords: ['c78','c103','activa','winwin','actiris','sine','ptp','jeunes','seniors','reduction onss','aide embauche','impulsion'] },
  { id: 'contratsmenu', label: 'Contrats & Docs',  icon: '📝', g: 2 },
  { id: 'gestionabs',  label: 'Absences & Congés', icon: '🗓', g: 2 },
  { id: 'conges',       label: 'Demandes Congés',  icon: '✅', g: 2 },
  { id: 'offboarding',    label: 'Offboarding',        icon: '👋', g: 2 },
  { id: 'dashrh',      label: 'Tableau de bord RH', icon: '📊', g: 2 },
  { id: 'portail',     label: 'Portail Employé',  icon: '🌐', g: 2 },
  { id: 'proceduresrh', label: 'Procédures RH',   icon: '📋', g: 2 },

  // ── PAIE ─────────────────────────────────────────────────────
  { id: '_g3', label: 'PAIE', icon: '💰', group: true },
  { id: 'payslip',       label: 'Fiches de Paie',    icon: '◈', g: 3 },
  { id: 'calcinstant',   label: 'Calcul & Simulation', icon: '🧮', g: 3 },
  { id: 'gestionprimes', label: 'Primes & Avantages', icon: '🎁', g: 3 },
  { id: 'cloture',       label: 'Clôture Mensuelle',  icon: '🔄', g: 3 },
  { id: 'historiquepayroll', label: 'Historique Paie',  icon: '📊', g: 3 },
  { id: 'fichespaiepdf',  label: 'Fiches PDF',         icon: '📑', g: 3 },
  { id: 'baremescp',     label: 'Barèmes & Seuils',   icon: '📐', g: 3 },

  // ── DÉCLARATIONS ─────────────────────────────────────────────
  { id: '_g4', label: 'DÉCLARATIONS', icon: '📡', group: true },
  { id: 'declarations',  label: 'ONSS & Dimona',      icon: '📡', g: 4 },
  { id: 'exportcompta',  label: 'Exports Comptables', icon: '📤', g: 4 },
  { id: 'connecteurscompta', label: 'BOB / WinBooks', icon: '📒', g: 4 },
  { id: 'sepa',          label: 'SEPA Virements',     icon: '💳', g: 4 },
  { id: 'belcotax281',   label: 'Belcotax 281.xx',    icon: '📊', g: 4, keywords: ['belcotax','281','fiche fiscale','finprof'] },
  { id: 'documentsociaux', label: 'Documents Sociaux DRS', icon: '📑', g: 4, keywords: ['drs','c4','c78','c103','inami','chomage','attestation','document social','formulaire'] },
  { id: 'decava', label: 'DECAVA — Véhicules Mixtes', icon: '🚗', g: 4, keywords: ['decava','vehicule','voiture','tva voiture','atn','avantage nature','co2','usage mixte'] },
  { id: 'assuranceloi', label: 'Assurance-Loi AT', icon: '🛡️', g: 2, keywords: ['assurance loi','accident travail','at','fedris','sinistre','prime at','declaration accident','police at'] },
  { id: 'chequesrepas', label: 'Chèques-Repas', icon: '🍽️', g: 3, keywords: ['cheques repas','sodexo','edenred','monizze','titre repas'] },
  { id: 'netaubrut', label: 'Net au Brut', icon: '⚖️', g: 3, keywords: ['net au brut','brut au net','calcul salaire','salaire net','salaire brut'] },
  { id: 'caissevacances', label: 'Caisse de Vacances', icon: '🏖️', g: 3, keywords: ['caisse vacances','pecule vacances','onva','ouvriers vacances'] },
  { id: 'listingtva',     label: 'Listing Annuel TVA',  icon: '📋', g: 4 },
  { id: 'belcotaxmandat', label: 'Mandat Belcotax',     icon: '📄', g: 4 },
  { id: 'rapports',      label: 'Rapports',           icon: '📈', g: 4 },
  { id: 'facturation',   label: 'Facturation',        icon: '🧾', g: 4 },

  // ── COMMERCIAL ───────────────────────────────────────────────
  { id: '_g5', label: 'COMMERCIAL', icon: '🎯', group: true },
  { id: 'diagnostic',      label: 'Diagnostic Client',  icon: '🔍', g: 5 },
  { id: 'checklistclient', label: 'Checklist Reprise',  icon: '✅', g: 5 },
  { id: 'comparatif',      label: 'Comparatif Marché',  icon: '⚔️', g: 5 },
  { id: 'guidecommercial', label: 'Guide Commercial',   icon: '📖', g: 5 },
  { id: 'mandatonss',      label: 'Mandats & Primes',   icon: '🏛', g: 5 },

  // ── ADMINISTRATION ───────────────────────────────────────────
  { id: '_g6', label: 'ADMINISTRATION', icon: '⚙️', group: true },
  { id: 'permissions',      label: 'Rôles & Accès',     icon: '🔐', g: 6 },
  { id: 'webhooks',         label: 'Webhooks API',       icon: '🔗', g: 6 },
  { id: 'backup',           label: 'Backup & Restore',  icon: '💾', g: 6 },
  { id: 'demandes_acces',    label: "Demandes d'accès",   icon: '🔑', g: 6 },
  { id: '2fa',               label: '2FA / TOTP',         icon: '🔐', g: 6 },
  { id: 'auditsecuritecode', label: 'Audit Sécurité',   icon: '🛡', g: 6 },
  { id: 'audittrail',       label: 'Audit Trail',       icon: '🔍', g: 6 },
  { id: 'admin',            label: 'Paramètres',        icon: '⚙️', g: 6 },
  // ── MODULES SUPPLÉMENTAIRES (tous searchables) ──────────────
  { id: 'accidentTravail',    label: 'Accident du Travail',      icon: '🚑', g: 2 },
  { id: 'actionsrapides',     label: 'Actions Rapides',          icon: '⚡', g: 7 },
  { id: 'activabruxelles',    label: 'Activa Bruxelles',         icon: '🏅', g: 6 },
  { id: 'adminbaremes',       label: 'Admin Barèmes',            icon: '⚙️', g: 7 },
  { id: 'gestionsocietes',    label: 'Gestion Sociétés',         icon: '🏢', g: 7 },
  { id: 'migrations', label: 'Migrations DB', icon: '⚙️', g: 7, keywords: ['migration','pgcrypto','rls','niss','iban','chiffrement','base de donnees','db','supabase','securite'] },
  { id: 'analytics',          label: 'Analytics & KPIs',         icon: '📈', g: 4 },
  { id: 'annexeReglement',    label: 'Annexe Règlement',         icon: '📜', g: 3 },
  { id: 'archives',           label: 'Archives GED',             icon: '🗄', g: 7 },
  { id: 'art60cpas',          label: 'Art. 60 CPAS',             icon: '🏢', g: 6 },
  { id: 'aureussuite',        label: 'Aureus IA Suite',          icon: '🔷', g: 7 },
  { id: 'authroles',          label: 'Rôles & Permissions',      icon: '🔐', g: 7 },
  { id: 'autopilot',          label: 'Autopilot',                icon: '🤖', g: 7 },
  { id: 'avantages',          label: 'Avantages & Rémunération', icon: '★', g: 3 },
  { id: 'baremespp',          label: 'Barèmes PP SPF',           icon: '📋', g: 3 },
  { id: 'batchdecl',          label: 'Déclarations Batch',       icon: '📋', g: 4 },
  { id: 'bilansocial',        label: 'Bilan Social',             icon: '📋', g: 5 },
  { id: 'budget',             label: 'Budget Prévisionnel',      icon: '💰', g: 4 },
  { id: 'calcmaladie',        label: 'Calcul Maladie',           icon: '🏥', g: 3 },
  { id: 'calendrier',         label: 'Calendrier Social',        icon: '📅', g: 3 },
  { id: 'ccts',               label: 'Conventions CCT',          icon: '📜', g: 5 },
  { id: 'cgvsaas',            label: 'CGV & Contrat SaaS',       icon: '📄', g: 7 },
  { id: 'changelog',          label: 'Changelog',                icon: '📋', g: 7 },
  { id: 'chargessociales',    label: 'Charges Sociales',         icon: '🏛', g: 4 },
  { id: 'chomagetemporaire',  label: 'Chômage Temporaire',       icon: '⏸', g: 4 },
  { id: 'commandcenter',      label: 'Command Center',           icon: '🎯', g: 1 },
  { id: 'comparateur',        label: 'Comparateur Salarial',     icon: '⚖', g: 3 },
  { id: 'compliance',         label: 'Compliance Radar',         icon: '🛡', g: 7 },
  { id: 'compteIndividuel',   label: 'Compte Individuel',        icon: '📄', g: 3 },
  { id: 'compteindividuelannuel', label: 'Compte Individuel Annuel', icon: '📄', g: 5 },
  { id: 'connexionshub',      label: 'Hub Connexions',           icon: '🔗', g: 7 },
  { id: 'contratgen',         label: 'Générateur Contrats',      icon: '📝', g: 2 },
  { id: 'coutsannuel',        label: 'Coûts Annuels',            icon: '📊', g: 3 },
  { id: 'couttotal',          label: 'Coût Total Employeur',     icon: '💰', g: 3 },
  { id: 'dashabsent',         label: 'Dashboard Absentéisme',    icon: '📊', g: 2 },
  { id: 'delegations',        label: 'Délégations Syndicales',   icon: '🏛', g: 5 },
  { id: 'demandesconges',     label: 'Demandes Congés',          icon: '📅', g: 2 },
  { id: 'demodonnees',        label: 'Données de Démo',          icon: '📦', g: 7 },
  { id: 'diagnosticv',        label: 'Diagnostic Prospect',      icon: '🎯', g: 6 },
  { id: 'echeancier',         label: 'Échéancier Paiements',     icon: '💳', g: 4 },
  { id: 'egalitehf',          label: 'Égalité H/F',              icon: '⚖️', g: 5 },
  { id: 'electionsociales',   label: 'Élections Sociales',       icon: '🗳', g: 5 },
  { id: 'exportWinbooks',     label: 'Export WinBooks/BOB',      icon: '📤', g: 4 },
  { id: 'exportbatch',        label: 'Export Batch',             icon: '📦', g: 4 },
  { id: 'exportcoda',         label: 'Export CODA',              icon: '🏦', g: 4 },
  { id: 'exportcomptapro',    label: 'Export Compta Pro',        icon: '📒', g: 4 },
  { id: 'fichespaie',         label: 'Fiches de Paie PDF',       icon: '◈', g: 3 },
  { id: 'fiduciaire',         label: 'Hub Fiduciaire',           icon: '🏢', g: 6 },
  { id: 'fiscal',             label: 'Fiscal',                   icon: '◇', g: 4 },
  { id: 'flexijobs',          label: 'Flexi-Jobs',               icon: '⚡', g: 3 },
  { id: 'formC131',           label: 'Certificat Vacances C131', icon: '🏖', g: 3 },
  { id: 'formC4',             label: 'Formulaire C4',            icon: '📋', g: 2 },
  { id: 'formationsec',       label: 'Formation & Sécurité',     icon: '🎓', g: 5 },
  { id: 'ged',                label: 'GED Documents',            icon: '📁', g: 7 },
  { id: 'gendocsjur',         label: 'Docs Juridiques',          icon: '📜', g: 6 },
  { id: 'guidefiduciaire',    label: 'Guide Fiduciaire',         icon: '📖', g: 6 },
  { id: 'importcsv',          label: 'Import CSV',               icon: '📥', g: 4 },
  { id: 'integrations',       label: 'Intégrations',             icon: '🔌', g: 7 },
  { id: 'interimaires',       label: 'Intérimaires',             icon: '👷', g: 2 },
  { id: 'journal',            label: 'Journal Activité',         icon: '📋', g: 1 },
  { id: 'joursPrestes',       label: 'Jours Prestés',            icon: '📅', g: 2 },
  { id: 'lanceursalerte',     label: "Lanceurs d'Alerte",        icon: '🚨', g: 5 },
  { id: 'legal',              label: 'Juridique & Veille',       icon: '⚖', g: 6 },
  { id: 'massengine',         label: 'Mass Engine',              icon: '🏭', g: 7 },
  { id: 'mentionslegales',    label: 'Mentions Légales',         icon: '📜', g: 7 },
  { id: 'monitoring',         label: 'Monitoring',               icon: '🖥', g: 7 },
  { id: 'offboarding_suite',  label: 'Offboarding',              icon: '🚪', g: 2 },
  { id: 'onboardwizard',      label: 'Onboarding Wizard',        icon: '🚀', g: 2 },
  { id: 'optifiscale',        label: 'Optimisation Fiscale',     icon: '💡', g: 3 },
  { id: 'parserConcurrent',   label: 'Audit Concurrent',         icon: '🔍', g: 6 },
  { id: 'payrollhistory',     label: 'Historique Paie',          icon: '📊', g: 3 },
  { id: 'piloteauto',         label: 'Pilote Auto Total',        icon: '🏎️', g: 7 },
  { id: 'plandiversite',      label: 'Plan Diversité',           icon: '🌍', g: 5 },
  { id: 'planifconges',       label: 'Planning Congés',          icon: '📅', g: 2 },
  { id: 'portailclient',      label: 'Portail Client',           icon: '🌐', g: 2 },
  { id: 'portalmanager',      label: 'Gestion Portails',         icon: '🏢', g: 7 },
  { id: 'queue',              label: 'File de Traitement',       icon: '📋', g: 7 },
  { id: 'rapportce',          label: 'Rapport Annuel CE',        icon: '🏛', g: 5 },
  { id: 'rapportsrole',       label: 'Rapports par Rôle',        icon: '📈', g: 4 },
  { id: 'registrepersonnel',  label: 'Registre du Personnel',    icon: '📖', g: 2 },
  { id: 'regulPP',            label: 'Régularisation PP',        icon: '📊', g: 4 },
  { id: 'reporting',          label: 'Reporting & Export',       icon: '▤', g: 4 },
  { id: 'reportingpro',       label: 'Reporting Pro',            icon: '📊', g: 4 },
  { id: 'repriseclient',      label: 'Reprise Concurrent',       icon: '🔄', g: 6 },
  { id: 'rh',                 label: 'RH & Workflows',           icon: '◉', g: 2 },
  { id: 'roadmapinfra',       label: 'Roadmap Infrastructure',   icon: '🗺', g: 7 },
  { id: 'salaires',           label: 'Salaires & Calculs',       icon: '◈', g: 3 },
  { id: 'securitedata',       label: 'Sécurité Données',         icon: '🔒', g: 7 },
  { id: 'seuilssociaux',      label: 'Seuils Sociaux',           icon: '📐', g: 5 },
  { id: 'simembauche',        label: 'Simulateur Embauche',      icon: '🧮', g: 3 },
  { id: 'simulateurspro',     label: 'Simulateurs Pro',          icon: '🔬', g: 3 },
  { id: 'simulicenciement',   label: 'Simulation Licenciement',  icon: '⚖️', g: 3 },
  { id: 'simupension',        label: 'Simulateur Pension',       icon: '🏖', g: 3 },
  { id: 'simutp',             label: 'Temps Partiel',            icon: '⏱', g: 3 },
  { id: 'creditemps',         label: 'Crédit-Temps',             icon: '🔄', g: 3, keywords: ['credit temps','cct103','conge','reduction carriere','allocation onem'] },
  { id: 'subscriptions',      label: 'Plans & Abonnements',      icon: '💳', g: 6, keywords: ['abonnement','plan','pricing','mrr','starter','pro','fiduciaire'] },
  { id: 'social',             label: 'Social & Assurances',      icon: '◆', g: 5 },
  { id: 'soldetoutcompte',    label: 'Solde Tout Compte',        icon: '📑', g: 3 },
  { id: 'support',            label: 'Support & Tickets',        icon: '🎫', g: 7 },
  { id: 'tbdirection',        label: 'Tableau Direction',        icon: '📊', g: 1 },
  { id: 'team',               label: 'Équipe',                   icon: '👥', g: 7 },
  { id: 'testsuite',          label: 'Test Suite',               icon: '🧪', g: 7 },
  { id: 'timeline',           label: 'Timeline Paie',            icon: '📅', g: 3 },
  { id: 'validation',         label: 'Validation Pré-Paie',      icon: '✅', g: 3 },
  { id: 'vehiculesatn',       label: 'Véhicules & ATN',          icon: '🚗', g: 3 },
  { id: 'workflowAbs',        label: 'Workflow Absences',        icon: '🏖', g: 2 },
];

export const GROUPS = MENU.filter(m => m.group);
export const getGroupItems = (gNum) => MENU.filter(m => m.g === gNum && !m.group);

// ═══ REDIRECTIONS — ancien id → nouveau id (pour les liens qui persistent) ═══
// Permet de garder la compatibilité avec les anciens cas dans layout-client.js
export const MENU_REDIRECTS = {
  // Accueil
  commandcenter:   'dashboard',
  tbdirection:     'dashboard',
  journal:         'notifications',
  smartalerts:     'notifications',
  actionsrapides:  'dashboard',
  // Employés
  dashabsent:      'gestionabs',
  planifconges:    'gestionabs',
  workflowAbs:     'gestionabs',
  accidentTravail: 'gestionabs',
  joursPrestes:    'gestionabs',
  interimaires:    'employees',
  registrepersonnel: 'employees',
  rh:              'dashrh',
  onboardwizard:   'onboarding',
  contratgen:      'contratsmenu',
  formC4:          'contratsmenu',
  formC131:        'contratsmenu',
  portailclient:   'portail',
  portalmanager:   'portail',
  // Paie
  salaires:        'payslip',
  validation:      'cloture',
  timeline:        'cloture',
  budget:          'cloture',
  simembauche:     'calcinstant',
  simutp:          'calcinstant',
  comparateur:     'calcinstant',
  simulateurspro:  'calcinstant',
  simulicenciement:'calcinstant',
  simupension:     'calcinstant',
  optifiscale:     'calcinstant',
  couttotal:       'calcinstant',
  avantages:       'gestionprimes',
  vehiculesatn:    'gestionprimes',
  flexijobs:       'gestionprimes',
  baremespp:       'baremescp',
  seuilssociaux:   'baremescp',
  calcmaladie:     'baremescp',
  calendrier:      'baremescp',
  soldetoutcompte: 'payslip',
  compteIndividuel:'payslip',
  compteindividuelannuel: 'payslip',
  regulPP:         'payslip',
  autoindex:       'payslip',
  coutsannuel:     'rapports',
  echeancier:      'rapports',
  annexeReglement: 'contratsmenu',
  // Déclarations
  onss:            'declarations',
  batchdecl:       'declarations',
  chargessociales: 'declarations',
  chomagetemporaire:'declarations',
  exportWinbooks:  'exportcompta',
  bob50:           'connecteurscompta',
  bob360:          'connecteurscompta',
  winbooks:        'connecteurscompta',
  winbooksconnect: 'connecteurscompta',
  bobwinbooks:     'connecteurscompta',
  importbob:       'connecteurscompta',
  exportcomptapro: 'exportcompta',
  exportcoda:      'exportcompta',
  exportbatch:     'exportcompta',
  importcsv:       'exportcompta',
  reporting:       'rapports',
  reportingpro:    'rapports',
  analytics:       'rapports',
  rapportsrole:    'rapports',
  auditfiscale:    'rapports',
  rapportce:       'rapports',
  bilansocial:     'rapports',
  fiscal:          'rapports',
  // Commercial
  diagnosticv:     'diagnostic',
  fiduciaire:      'guidecommercial',
  guidefiduciaire: 'guidecommercial',
  landing:         'guidecommercial',
  parserConcurrent:'comparatif',
  repriseclient:   'checklistclient',
  gendocsjur:      'contratsmenu',
  legal:           'contratsmenu',
  // Mandats (fusionnés sous mandatonss)
  belcotaxmandat:  'mandatonss',
  domiciliation:   'mandatonss',
  premieremploi:   'mandatonss',
  activabruxelles: 'mandatonss',
  art60cpas:       'mandatonss',
  impulsion55:     'mandatonss',
  monbee:          'mandatonss',
  connexionshub:   'mandatonss',
  // Concertation sociale → fusionné dans baremescp ou proceduresrh
  ccts:            'baremescp',
  delegations:     'proceduresrh',
  delegationsyndicale: 'proceduresrh',
  egalitehf:       'proceduresrh',
  electionsociales:'proceduresrh',
  formationsec:    'proceduresrh',
  lanceursalerte:  'proceduresrh',
  plandiversite:   'proceduresrh',
  social:          'proceduresrh',
  // Admin
  authroles:       'permissions',
  adminbaremes:    'admin',
  archives:        'admin',
  auditfiscale:    'auditsecuritecode',
  aureussuite:     'admin',
  autopilot:       'admin',
  piloteauto:      'admin',
  cgvsaas:         'admin',
  changelog:       'admin',
  compliance:      'auditsecuritecode',
  demodonnees:     'admin',
  ged:             'admin',
  historique:      'admin',
  integrations:    'admin',
  massengine:      'admin',
  mentionslegales: 'admin',
  monitoring:      'admin',
  queue:           'admin',
  rgpd:            'auditsecuritecode',
  roadmapinfra:    'admin',
  securitedata:    'auditsecuritecode',
  support:         'admin',
  testsuite:       'auditsecuritecode',
  team:            'admin',
  autoindex:       'payslip',
};

// ═══ INDEX SOUS-SECTIONS — RECHERCHE CONTEXTUELLE ═══
export const SEARCH_SUBSECTIONS = [
  { id: 'payslip', anchor: 'section-onss-cotisations', icon: '⚡', label: 'ONSS & Cotisations',
    sub: 'Fiche de paie', keywords: ['onss','cotisation','13,07','25,07','securite sociale','patronal','ouvrier'] },
  { id: 'payslip', anchor: 'section-precompte', icon: '🧾', label: 'Précompte professionnel',
    sub: 'Fiche de paie', keywords: ['precompte','pp','impot','tranches','taux','bonus emploi','fiscal'] },
  { id: 'payslip', anchor: 'section-csss', icon: '📊', label: 'CSSS',
    sub: 'Fiche de paie', keywords: ['csss','cotisation speciale','revenu imposable'] },
  { id: 'gestionprimes', anchor: 'section-avantages', icon: '🎁', label: 'Avantages & Frais propres',
    sub: 'Primes & Avantages', keywords: ['avantages','frais propres','cheques repas','eco cheques','teletravail','km','kilometrique'] },
  { id: 'payslip', anchor: 'section-saisies', icon: '⚖️', label: 'Saisies sur salaire',
    sub: 'Fiche de paie', keywords: ['saisie','art 1409','garnish','immunite'] },
  { id: 'baremescp', anchor: 'section-cp', icon: '📋', label: 'Barème sectoriel CP',
    sub: 'Barèmes & Seuils', keywords: ['bareme','cp','commission paritaire','sectoriel','minimum','cp 200','cp 111','cp 118'] },
];

