// ═══ MENU CONFIGURATION — 5 GROUPES, 35 ITEMS ═══
// Refactorisé : suppression des 107 doublons et items techniques inutiles
// Les fonctions avancées sont accessibles via onglets internes aux pages

export const MENU = [

  // ── ACCUEIL ──────────────────────────────────────────────────
  { id: '_g1', label: 'ACCUEIL', icon: '◫', group: true },
  { id: 'dashboard',   label: 'Dashboard',      icon: '◫', g: 1 },
  { id: 'embaucheaz',  label: 'Embauche A→Z',   icon: '🚀', g: 1 },
  { id: 'notifications', label: 'Notifications', icon: '🔔', g: 1 },

  // ── EMPLOYÉS ─────────────────────────────────────────────────
  { id: '_g2', label: 'EMPLOYÉS', icon: '👥', group: true },
  { id: 'employees',    label: 'Liste & Fiches',   icon: '👤', g: 2 },
  { id: 'onboarding',  label: 'Nouvel employé',   icon: '🆕', g: 2 },
  { id: 'contratsmenu', label: 'Contrats & Docs',  icon: '📝', g: 2 },
  { id: 'gestionabs',  label: 'Absences & Congés', icon: '🗓', g: 2 },
  { id: 'conges',       label: 'Demandes Congés',  icon: '✅', g: 2 },
  { id: 'dashrh',      label: 'Tableau de bord RH', icon: '📊', g: 2 },
  { id: 'portail',     label: 'Portail Employé',  icon: '🌐', g: 2 },
  { id: 'proceduresrh', label: 'Procédures RH',   icon: '📋', g: 2 },

  // ── PAIE ─────────────────────────────────────────────────────
  { id: '_g3', label: 'PAIE', icon: '💰', group: true },
  { id: 'payslip',       label: 'Fiches de Paie',    icon: '◈', g: 3 },
  { id: 'calcinstant',   label: 'Calcul & Simulation', icon: '🧮', g: 3 },
  { id: 'gestionprimes', label: 'Primes & Avantages', icon: '🎁', g: 3 },
  { id: 'cloture',       label: 'Clôture Mensuelle',  icon: '🔄', g: 3 },
  { id: 'baremescp',     label: 'Barèmes & Seuils',   icon: '📐', g: 3 },

  // ── DÉCLARATIONS ─────────────────────────────────────────────
  { id: '_g4', label: 'DÉCLARATIONS', icon: '📡', group: true },
  { id: 'declarations',  label: 'ONSS & Dimona',      icon: '📡', g: 4 },
  { id: 'exportcompta',  label: 'Exports Comptables', icon: '📤', g: 4 },
  { id: 'connecteurscompta', label: 'BOB / WinBooks', icon: '📒', g: 4 },
  { id: 'sepa',          label: 'SEPA Virements',     icon: '💳', g: 4 },
  { id: 'belcotax281',   label: 'Belcotax 281.10',    icon: '📊', g: 4 },
  { id: 'rapports',      label: 'Rapports',           icon: '📈', g: 4 },
  { id: 'facturation',   label: 'Facturation',        icon: '🧾', g: 4 },

  // ── COMMERCIAL ───────────────────────────────────────────────
  { id: '_g5', label: 'COMMERCIAL', icon: '🎯', group: true },
  { id: 'diagnostic',      label: 'Diagnostic Client',  icon: '🔍', g: 5 },
  { id: 'checklistclient', label: 'Checklist Reprise',  icon: '✅', g: 5 },
  { id: 'comparatif',      label: 'Comparatif Marché',  icon: '⚔️', g: 5 },
  { id: 'guidecommercial', label: 'Guide Commercial',   icon: '📖', g: 5 },
  { id: 'mandatonss',      label: 'Mandats & Primes',   icon: '🏛', g: 5 },

  // ── ADMINISTRATION ───────────────────────────────────────────
  { id: '_g6', label: 'ADMINISTRATION', icon: '⚙️', group: true },
  { id: 'permissions',      label: 'Rôles & Accès',     icon: '🔐', g: 6 },
  { id: 'backup',           label: 'Backup & Restore',  icon: '💾', g: 6 },
  { id: 'auditsecuritecode', label: 'Audit Sécurité',   icon: '🛡', g: 6 },
  { id: 'audittrail',       label: 'Audit Trail',       icon: '🔍', g: 6 },
  { id: 'admin',            label: 'Paramètres',        icon: '⚙️', g: 6 },
];

export const GROUPS = MENU.filter(m => m.group);
export const getGroupItems = (gNum) => MENU.filter(m => m.g === gNum && !m.group);

// ═══ REDIRECTIONS — ancien id → nouveau id (pour les liens qui persistent) ═══
// Permet de garder la compatibilité avec les anciens cas dans layout-client.js
export const MENU_REDIRECTS = {
  // Accueil
  commandcenter:   'dashboard',
  tbdirection:     'dashboard',
  journal:         'notifications',
  smartalerts:     'notifications',
  actionsrapides:  'dashboard',
  // Employés
  dashabsent:      'gestionabs',
  planifconges:    'gestionabs',
  workflowAbs:     'gestionabs',
  accidentTravail: 'gestionabs',
  joursPrestes:    'gestionabs',
  interimaires:    'employees',
  registrepersonnel: 'employees',
  rh:              'dashrh',
  onboardwizard:   'onboarding',
  contratgen:      'contratsmenu',
  formC4:          'contratsmenu',
  formC131:        'contratsmenu',
  portailclient:   'portail',
  portalmanager:   'portail',
  // Paie
  salaires:        'payslip',
  validation:      'cloture',
  timeline:        'cloture',
  budget:          'cloture',
  simembauche:     'calcinstant',
  simutp:          'calcinstant',
  comparateur:     'calcinstant',
  simulateurspro:  'calcinstant',
  simulicenciement:'calcinstant',
  simupension:     'calcinstant',
  optifiscale:     'calcinstant',
  couttotal:       'calcinstant',
  avantages:       'gestionprimes',
  vehiculesatn:    'gestionprimes',
  flexijobs:       'gestionprimes',
  baremespp:       'baremescp',
  seuilssociaux:   'baremescp',
  calcmaladie:     'baremescp',
  calendrier:      'baremescp',
  soldetoutcompte: 'payslip',
  compteIndividuel:'payslip',
  compteindividuelannuel: 'payslip',
  regulPP:         'payslip',
  autoindex:       'payslip',
  coutsannuel:     'rapports',
  echeancier:      'rapports',
  annexeReglement: 'contratsmenu',
  // Déclarations
  onss:            'declarations',
  batchdecl:       'declarations',
  chargessociales: 'declarations',
  chomagetemporaire:'declarations',
  exportWinbooks:  'exportcompta',
  bob50:           'connecteurscompta',
  bob360:          'connecteurscompta',
  winbooks:        'connecteurscompta',
  winbooksconnect: 'connecteurscompta',
  bobwinbooks:     'connecteurscompta',
  importbob:       'connecteurscompta',
  exportcomptapro: 'exportcompta',
  exportcoda:      'exportcompta',
  exportbatch:     'exportcompta',
  importcsv:       'exportcompta',
  reporting:       'rapports',
  reportingpro:    'rapports',
  analytics:       'rapports',
  rapportsrole:    'rapports',
  auditfiscale:    'rapports',
  rapportce:       'rapports',
  bilansocial:     'rapports',
  fiscal:          'rapports',
  // Commercial
  diagnosticv:     'diagnostic',
  fiduciaire:      'guidecommercial',
  guidefiduciaire: 'guidecommercial',
  landing:         'guidecommercial',
  parserConcurrent:'comparatif',
  repriseclient:   'checklistclient',
  gendocsjur:      'contratsmenu',
  legal:           'contratsmenu',
  // Mandats (fusionnés sous mandatonss)
  belcotaxmandat:  'mandatonss',
  domiciliation:   'mandatonss',
  premieremploi:   'mandatonss',
  activabruxelles: 'mandatonss',
  art60cpas:       'mandatonss',
  impulsion55:     'mandatonss',
  monbee:          'mandatonss',
  connexionshub:   'mandatonss',
  // Concertation sociale → fusionné dans baremescp ou proceduresrh
  ccts:            'baremescp',
  delegations:     'proceduresrh',
  delegationsyndicale: 'proceduresrh',
  egalitehf:       'proceduresrh',
  electionsociales:'proceduresrh',
  formationsec:    'proceduresrh',
  lanceursalerte:  'proceduresrh',
  plandiversite:   'proceduresrh',
  social:          'proceduresrh',
  // Admin
  authroles:       'permissions',
  adminbaremes:    'admin',
  archives:        'admin',
  auditfiscale:    'auditsecuritecode',
  aureussuite:     'admin',
  autopilot:       'admin',
  piloteauto:      'admin',
  cgvsaas:         'admin',
  changelog:       'admin',
  compliance:      'auditsecuritecode',
  demodonnees:     'admin',
  ged:             'admin',
  historique:      'admin',
  integrations:    'admin',
  massengine:      'admin',
  mentionslegales: 'admin',
  monitoring:      'admin',
  queue:           'admin',
  rgpd:            'auditsecuritecode',
  roadmapinfra:    'admin',
  securitedata:    'auditsecuritecode',
  support:         'admin',
  testsuite:       'auditsecuritecode',
  team:            'admin',
  autoindex:       'payslip',
};

// ═══ INDEX SOUS-SECTIONS — RECHERCHE CONTEXTUELLE ═══
export const SEARCH_SUBSECTIONS = [
  { id: 'payslip', anchor: 'section-onss-cotisations', icon: '⚡', label: 'ONSS & Cotisations',
    sub: 'Fiche de paie', keywords: ['onss','cotisation','13,07','25,07','securite sociale','patronal','ouvrier'] },
  { id: 'payslip', anchor: 'section-precompte', icon: '🧾', label: 'Précompte professionnel',
    sub: 'Fiche de paie', keywords: ['precompte','pp','impot','tranches','taux','bonus emploi','fiscal'] },
  { id: 'payslip', anchor: 'section-csss', icon: '📊', label: 'CSSS',
    sub: 'Fiche de paie', keywords: ['csss','cotisation speciale','revenu imposable'] },
  { id: 'gestionprimes', anchor: 'section-avantages', icon: '🎁', label: 'Avantages & Frais propres',
    sub: 'Primes & Avantages', keywords: ['avantages','frais propres','cheques repas','eco cheques','teletravail','km','kilometrique'] },
  { id: 'payslip', anchor: 'section-saisies', icon: '⚖️', label: 'Saisies sur salaire',
    sub: 'Fiche de paie', keywords: ['saisie','art 1409','garnish','immunite'] },
  { id: 'baremescp', anchor: 'section-cp', icon: '📋', label: 'Barème sectoriel CP',
    sub: 'Barèmes & Seuils', keywords: ['bareme','cp','commission paritaire','sectoriel','minimum','cp 200','cp 111','cp 118'] },
];
