const fs=require('fs');
const code=// AUREUS SOCIAL PRO Email API - NO auth check - v2
function sanitizeHTML(h){if(!h)return'';return h.replace(/<script[\\s\\S]*?<\\/script>/gi,'').replace(/<iframe[\\s\\S]*?<\\/iframe>/gi,'').replace(/javascript\\s*:/gi,'blocked:');}
function isValidEmail(e){return/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(e);}
async function sendRetry(p,k){let err=null;for(let a=0;a<3;a++){try{const res=await fetch('https://api.resend.com/emails',{method:'POST',headers:{'Authorization':'Bearer '+k,'Content-Type':'application/json'},body:JSON.stringify(p)});const d=await res.json();if(res.ok)return{success:true,data:d};err=d;}catch(e){err={message:e.message};}}return{success:false,error:err};}
export async function POST(request){try{const body=await request.json();const{to,subject,html,attachments,from}=body;if(!to||!subject)return Response.json({error:'Missing to or subject'},{status:400});const recipients=Array.isArray(to)?to:[to];const apiKey=process.env.RESEND_API_KEY;if(!apiKey){return Response.json({success:true,mode:'dev',message:'RESEND_API_KEY non configuree',to,subject});}const payload={from:from||'Aureus Social Pro <noreply@aureussocial.be>',to:recipients,subject:subject.slice(0,500),html:sanitizeHTML(html)||'<p>Message Aureus</p>'};if(attachments&&attachments.length>0){payload.attachments=attachments.slice(0,5).map(a=>({filename:(a.filename||'doc.pdf').slice(0,100),content:a.content}));}const result=await sendRetry(payload,apiKey);if(!result.success)return Response.json({success:false,error:result.error},{status:502});return Response.json({success:true,mode:'resend',id:result.data.id,to:payload.to,subject});}catch(e){return Response.json({error:e.message},{status:500});}}
export async function GET(){const k=!!process.env.RESEND_API_KEY;return Response.json({service:'Aureus Email API',resend:k?'configured':'NOT configured',keyPrefix:k?process.env.RESEND_API_KEY.substring(0,6)+'...':'none'});};
fs.writeFileSync('app/api/send-email/route.js',code,'utf8');
console.log('OK - route.js rewritten completely');
