'use client';
import { useState } from 'react';
export { ActionsRapides, ArchivesNumeriques, AuditTrail, AuthMultiRoles, MonitoringSante, RGPDManager, SecuriteData, TestSuiteDash } from './AdminGroup';
export { AnalyticsDash, CommandCenter, JournalActivite, SmartAlerts, TableauBordDirection, TableauDirection } from './DashboardGroup';
export { AutoIndexation, BudgetPrev, CalcJoursPrestes, Echeancier, EcheancierPaiements, GestionPrimes, PayrollTimeline, RecapEmployeur, RegulPPAnnuelle, SimuOptiFiscale, ValidationEngine } from './PayrollGroup';
export { AutomationHub, HistoriquePilote, MassEngine, PiloteAuto, ProcessingQueue, SmartAutomation, SmartAutopilot } from './AutomationGroup';
export { CalendrierSocial, ChecklistClient, ContratGenerator, ConventionsCollectives, GestionVehicules, OnboardingWizard, PortailEmploye, PromesseEmbauche, WorkflowAbsences } from './HRGroup';
export { ComingSoon, SetupWizard } from './UtilsGroup';
export { ComparatifConcurrents, IntegrationsHub, LandingPage, ParserImportConcurrent, PortalManager } from './CommercialGroup';
export { EnvoiMasse, ExportWinbooks, FacturationTarif } from './DeclarationsGroup';
