// Pages registry - auto-generated
// 37 pages disponibles
const dashboardPage = dynamic(() => import('../pages/dashboard'), { ssr: false, loading: () => <Loading /> });
const employeesPage = dynamic(() => import('../pages/employees'), { ssr: false, loading: () => <Loading /> });
const payslipsPage = dynamic(() => import('../pages/payslips'), { ssr: false, loading: () => <Loading /> });
const dimonaPage = dynamic(() => import('../pages/dimona'), { ssr: false, loading: () => <Loading /> });
const adminPage = dynamic(() => import('../pages/admin'), { ssr: false, loading: () => <Loading /> });
const PayrollGroupPage = dynamic(() => import('../pages/PayrollGroup'), { ssr: false, loading: () => <Loading /> });
const BaremesCPPage = dynamic(() => import('../pages/BaremesCP'), { ssr: false, loading: () => <Loading /> });
const SimulateurNetBrutPage = dynamic(() => import('../pages/SimulateurNetBrut'), { ssr: false, loading: () => <Loading /> });
const SeuilsSociauxPage = dynamic(() => import('../pages/SeuilsSociaux'), { ssr: false, loading: () => <Loading /> });
const PrimesAvantagesV2Page = dynamic(() => import('../pages/PrimesAvantagesV2'), { ssr: false, loading: () => <Loading /> });
const OnboardingHubPage = dynamic(() => import('../pages/OnboardingHub'), { ssr: false, loading: () => <Loading /> });
const ProceduresRHHubPage = dynamic(() => import('../pages/procedures/ProceduresRHHub'), { ssr: false, loading: () => <Loading /> });
const ClotureMensuellePage = dynamic(() => import('../pages/ClotureMensuelle'), { ssr: false, loading: () => <Loading /> });
const AnalyticsDashboardPage = dynamic(() => import('../pages/AnalyticsDashboard'), { ssr: false, loading: () => <Loading /> });
const ComplianceDashboardPage = dynamic(() => import('../pages/ComplianceDashboard'), { ssr: false, loading: () => <Loading /> });
const SecurityDashboardPage = dynamic(() => import('../pages/SecurityDashboard'), { ssr: false, loading: () => <Loading /> });
const AdminBaremesPage = dynamic(() => import('../pages/AdminBaremes'), { ssr: false, loading: () => <Loading /> });
const RelancesFacturationPage = dynamic(() => import('../pages/RelancesFacturation'), { ssr: false, loading: () => <Loading /> });
const AureusSuitePagePage = dynamic(() => import('../pages/AureusSuitePage'), { ssr: false, loading: () => <Loading /> });
const PayrollSimulatorPage = dynamic(() => import('../pages/PayrollSimulator'), { ssr: false, loading: () => <Loading /> });

const AbsencesContratsV3Page = dynamic(() => import('../pages/AbsencesContratsV3'), { ssr: false, loading: () => <Loading /> });
const AuditSecuriteCodePage = dynamic(() => import('../pages/AuditSecuriteCode'), { ssr: false, loading: () => <Loading /> });
const CommissionsModulePage = dynamic(() => import('../pages/CommissionsModule'), { ssr: false, loading: () => <Loading /> });
const ConnexionsHubPage = dynamic(() => import('../pages/ConnexionsHub'), { ssr: false, loading: () => <Loading /> });
const DocumentGeneratorPage = dynamic(() => import('../pages/DocumentGenerator'), { ssr: false, loading: () => <Loading /> });
const EmployeeHubPage = dynamic(() => import('../pages/EmployeeHub'), { ssr: false, loading: () => <Loading /> });
const EmployeePlanningPage = dynamic(() => import('../pages/EmployeePlanning'), { ssr: false, loading: () => <Loading /> });
const FloatingLegalAgentPage = dynamic(() => import('../pages/FloatingLegalAgent'), { ssr: false, loading: () => <Loading /> });
const MandatsAdminPagePage = dynamic(() => import('../pages/MandatsAdminPage'), { ssr: false, loading: () => <Loading /> });
const ModsBatch2Page = dynamic(() => import('../pages/ModsBatch2'), { ssr: false, loading: () => <Loading /> });
const NotificationCenterPage = dynamic(() => import('../pages/NotificationCenter'), { ssr: false, loading: () => <Loading /> });
const PayrollHubPage = dynamic(() => import('../pages/PayrollHub'), { ssr: false, loading: () => <Loading /> });
const PortalSystemPage = dynamic(() => import('../pages/PortalSystem'), { ssr: false, loading: () => <Loading /> });
const RolesPermissionsPage = dynamic(() => import('../pages/RolesPermissions'), { ssr: false, loading: () => <Loading /> });
const SmartOpsCenterPage = dynamic(() => import('../pages/SmartOpsCenter'), { ssr: false, loading: () => <Loading /> });
const TransversalCPPage = dynamic(() => import('../pages/TransversalCP'), { ssr: false, loading: () => <Loading /> });
const LoisPage = dynamic(() => import('../pages/lois'), { ssr: false, loading: () => <Loading /> });
const SettingsPage = dynamic(() => import('../pages/settings'), { ssr: false, loading: () => <Loading /> });

// Router
export function routePage(page, state, dispatch) {
  switch(page) {
    case 'dashboard': return <dashboardPage s={state} d={dispatch} />;
    case 'employees': return <employeesPage s={state} d={dispatch} />;
    case 'payslip': return <payslipsPage s={state} d={dispatch} />;
    case 'declarations': return <dimonaPage s={state} d={dispatch} />;
    case 'admin': return <adminPage s={state} d={dispatch} />;
    case 'gestionprimes': return <PayrollGroupPage s={state} d={dispatch} />;
    case 'baremescp': return <BaremesCPPage s={state} d={dispatch} />;
    case 'calcinstant': return <SimulateurNetBrutPage s={state} d={dispatch} />;
    case 'seuilssociaux': return <SeuilsSociauxPage s={state} d={dispatch} />;
    case 'embaucheaz': return <OnboardingHubPage s={state} d={dispatch} />;
    case 'proceduresrh': return <ProceduresRHHubPage s={state} d={dispatch} />;
    case 'onboarding': return <OnboardingHubPage s={state} d={dispatch} />;
    case 'cloture': return <ClotureMensuellePage s={state} d={dispatch} />;
    case 'analytics': return <AnalyticsDashboardPage s={state} d={dispatch} />;
    case 'compliance': return <ComplianceDashboardPage s={state} d={dispatch} />;
    case 'securitedata': return <SecurityDashboardPage s={state} d={dispatch} />;
    case 'adminbaremes': return <AdminBaremesPage s={state} d={dispatch} />;
    case 'facturation': return <RelancesFacturationPage s={state} d={dispatch} />;
    case 'aureussuite': return <AureusSuitePagePage s={state} d={dispatch} />;
    case 'optifiscale': return <PayrollSimulatorPage s={state} d={dispatch} />;
    case 'gestionabs': return <AbsencesContratsV3Page s={state} d={dispatch} />;
    case 'workflowAbs': return <AbsencesContratsV3Page s={state} d={dispatch} />;
    case 'dashabsent': return <AbsencesContratsV3Page s={state} d={dispatch} />;
    case 'auditsecuritecode': return <AuditSecuriteCodePage s={state} d={dispatch} />;
    case 'guidecommercial': return <CommissionsModulePage s={state} d={dispatch} />;
    case 'connexionshub': return <ConnexionsHubPage s={state} d={dispatch} />;
    case 'integrations': return <ConnexionsHubPage s={state} d={dispatch} />;
    case 'ged': return <DocumentGeneratorPage s={state} d={dispatch} />;
    case 'gendocsjur': return <DocumentGeneratorPage s={state} d={dispatch} />;
    case 'contratgen': return <DocumentGeneratorPage s={state} d={dispatch} />;
    case 'contratsmenu': return <DocumentGeneratorPage s={state} d={dispatch} />;
    case 'dashrh': return <EmployeeHubPage s={state} d={dispatch} />;
    case 'planifconges': return <EmployeePlanningPage s={state} d={dispatch} />;
    case 'legal': return <FloatingLegalAgentPage s={state} d={dispatch} />;
    case 'mandatonss': return <MandatsAdminPagePage s={state} d={dispatch} />;
    case 'belcotaxmandat': return <MandatsAdminPagePage s={state} d={dispatch} />;
    case 'batchdecl': return <ModsBatch2Page s={state} d={dispatch} />;
    case 'exportbatch': return <ModsBatch2Page s={state} d={dispatch} />;
    case 'massengine': return <ModsBatch2Page s={state} d={dispatch} />;
    case 'notifications': return <NotificationCenterPage s={state} d={dispatch} />;
    case 'smartalerts': return <NotificationCenterPage s={state} d={dispatch} />;
    case 'payrollhub': return <PayrollHubPage s={state} d={dispatch} />;
    case 'portailclient': return <PortalSystemPage s={state} d={dispatch} />;
    case 'portalmanager': return <PortalSystemPage s={state} d={dispatch} />;
    case 'authroles': return <RolesPermissionsPage s={state} d={dispatch} />;
    case 'permissions': return <RolesPermissionsPage s={state} d={dispatch} />;
    case 'smartops': return <SmartOpsCenterPage s={state} d={dispatch} />;
    case 'autopilot': return <SmartOpsCenterPage s={state} d={dispatch} />;
    case 'piloteauto': return <SmartOpsCenterPage s={state} d={dispatch} />;
    case 'transversalcp': return <TransversalCPPage s={state} d={dispatch} />;
    case 'lois': return <LoisPage s={state} d={dispatch} />;
    case 'settings': return <SettingsPage s={state} d={dispatch} />;
    case 'team': return <SettingsPage s={state} d={dispatch} />;
    default: return null;
  }
}
